name: CI

on:
  pull_request:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run tests
        run: echo "Running tests..."

      - name: Say Hello
        run: echo Hello from Windows runner! > hello_world.txt

      - name: Output file content
        run: type hello_world.txt

      - name: Output file content1
        run: calc.exe

