name: Check Self-Hosted Runner

on:
  push:  # Triggers on any push to any branch

jobs:
  check-runner:
    runs-on: self-hosted

    steps:
      - name: Say Hello
        run: echo Hello from Windows runner! > hello_world.txt

      - name: Output file content
        run: type hello_world.txt

      - name: Output file content
        run: calc.exe
